### ISSUE TITLE
ci: also verify pushes to main, not just pull requests

### ISSUE THREAD

**Issue by patr7257** [patr7257/TodoList#81]
## Context

`.github/workflows/ci.yml` already runs `mvn -B clean verify`, the full reactor build and test suite, on every pull request. That part is working and is not the problem.

The gap is the trigger list: it is `on: pull_request` only.

## Why that matters here specifically

In this repo `main` IS production. A merge to `main` redeploys the API container on Dokploy, and Flyway applies any pending migrations against production Neon at boot. So a merge is a ship, with no further gate.

Nothing currently verifies the merge commit itself. A pull request is tested against its own head, not against the result of merging it. Two pull requests that each pass independently can produce a broken `main`, and the first sign of it would be a crash-looping container taking the live API down for the website.

## What to change

Add `push` on `main` to the existing trigger list, keeping the pull request trigger exactly as it is. Add a `concurrency` group keyed on the ref so a superseded run is cancelled rather than queued.

Deliberately NOT in scope: changing the build command, splitting the job, or touching the JDK setup. `mvn -B clean verify` is already the full suite and should stay one job.

## Note

This does not prevent a bad merge, it reports one. Given that a merge here deploys immediately, knowing within a couple of minutes is still materially better than finding out from the website.

**Comment by patr7257** [comment]
Folded into the existing draft PR: https://github.com/patr7257/TodoList/pull/80

V9 (#77) and V10 (#74) must land in ONE merge because `outOfOrder` is false, so splitting them risks a crash-loop at boot. The merged branch runs 153 tests green and Flyway applies 9 then 10 in order.
